config/routes.rb
IthenaApp::Application.routes.draw do

  get "emle/index"

  resources :companies

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :mobiles, :only => [:create, :destroy, :update]
  resources :credit_cards, :only => [:create, :destroy, :update]

  match '/account', :to => 'pages#account'
  match '/about',   :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/faq',     :to => 'pages#faq'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root              :to => 'pages#home'
  

end

app/views/layouts/_header.html.erb
<header>
	<div id="tag-line">
		Granting wishes. Airtime in six seconds or less...
	</div>
	<a href="/"><%= image_tag("logo.png", :alt => "Sample App", :class => "round") %></a>
	<nav id="sub_nav">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Account", account_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact Us", contact_path %></li>
			<li><%= link_to "FAQs", faq_path %></li>
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
	<script src='https://github.com/janl/mustache.js/raw/master/mustache.js'></script>
  <%= csrf_meta_tags %>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">
	<%= javascript_include_tag "modernizr-2.0.6.min.js" %>
</head>

<body>

  <div id="container">
		<%= render 'layouts/header' %>
		<section class="round">
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
		  <% end %>
		</section>
		<div class="clearfix">
			<% if !@current_user.nil? %>
				<div id="page_content">
					<div id="left-col">
						<p id="navcontainer" class="hidden">adpage</p>
						<p id="navcol" class="hidden">gettingStarted</p>
						<div id="nav_col" class="smooth">
							<ul class="feed_filter selectable">
								<li><a href="/account" id="start" class="filter_link require_user smooth selected">Topup</a></li>
								<li><a href=<%= edit_user_path(@current_user)%> id="websites" class="filter_link smooth">Edit Account</a></li>
								<li><a href="/history" id="codegen" class="filter_link smooth">Transaction History</a></li>
								<li><a href="/bonuses" id="examples" class="filter_link smooth">Bonuses</a></li>
								<li><a href="#" id="refer-friend" class="filter_link smooth">Refer Friend</a></li>
							</ul>
						</div>
					</div>
				</div>
			<% else %>
			<% end %>	
  		<div id="main" role="main">
				<%= yield %>
  		</div>
		</div>
  		<footer>
				<%= render 'layouts/footer' %>
				<%= debug(params) if Rails.env.development? %>
  		</footer>
  </div> <!--! end of #container -->
	
  <!-- Change UA-XXXXX-X to be your site's ID -->
  <script>
    window._gaq = [['_setAccount','UAXXXXXXXX1'],['_trackPageview'],['_trackPageLoadTime']];
    Modernizr.load({
      load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
    });
  </script>


  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->
  
</body>
</html>